name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure
        run: npm config set '//npm.pkg.github.com/:_authToken' "${PAT}"
        env:
          PAT: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}