name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
